### ISSUE TITLE
Absolutelty no photo-related mimetype/ext

### ISSUE THREAD

**Issue by DeadcatDev** [jshttp/mime-db#104]
No .cr2 / .nef / .raw / .dng and others photo related mimetypes/ext

**Comment by dougwilson** [comment]
https://github.com/jshttp/mime-db/blob/master/README.md#contributing

**Comment by hueniverse** [comment]
Absolutely the wrong way to engage with open source.

**Comment by DeadcatDev** [comment]
@hueniverse ok, so than we can close our eyes and say that issue never happend ;) 

I just leave it to be known, no time at my point of live for contribute, sorry, maybe about january i will able to add them, but it's good to know. So keep calm ;)

**Comment by dougwilson** [comment]
Closing due to no movement for 3 months. You're still welcome to make a PR, but there is no clear indication for the timeline of closing the issue, so just trying to clean up.

**Comment by PierBover** [comment]
https://github.com/jshttp/mime-db/pull/219
