### ISSUE TITLE
Compressible definition for more mimetypes

### ISSUE THREAD

**Issue by danny0838** [jshttp/mime-db#114]
Follow the same logic in #110. I think we can add to custom-suffix.json that "+xml" as compressible and "+zip" as not compressible.

**Comment by dougwilson** [comment]
SGTM. For anyone who wants to make a PR on this, please split between two PRs :+1:

**Comment by rmzelle** [comment]
> I think we can add to custom-suffix.json that "+xml" as compressible and "+zip" as not compressible.

@danny0838, @dougwilson, I was wondering if this should be applied just to the existing contents of custom-suffix.json, or if new entries should also be added to custom-suffix.json to cover any aggregated data that ends up in db.json from other sources? If the former, the only chance to custom-suffix.json that's currently necessary would be to add `"compressible": true` to the definition of "application/dash+xml" (see https://github.com/jshttp/mime-db/pull/122/commits/638857e1817677818d33846bb11fc6e0504bfd0d).

**Comment by dougwilson** [comment]
> I was wondering if this should be applied just to the existing contents of custom-suffix.json

I'm not really following. The only thing in there is just the +json.

> or if new entries should also be added to custom-suffix.json to cover any aggregated data that ends up in db.json from other sources?

Isn't that what the request for this issue is?

> If the former, the only change to custom-suffix.json that's currently necessary would be to add "compressible": true to the definition of "application/dash+xml"

I'm not sure what this means. There is only one thing in custom-suffix.json and it's not application/dash+xml

**Comment by rmzelle** [comment]
Oh, sorry for the confusion. Where I wrote "custom-suffix.json" above I meant "custom-types.json".

**Comment by rmzelle** [comment]
Ah, I also realize I misunderstood @danny0838's proposal above. Just ignore me for now. Proper PR coming up.
