### ISSUE TITLE
Add mimetype application/x-maff 

### ISSUE THREAD

**Issue by danny0838** [jshttp/mime-db#115]
Source: http://maf.mozdev.org/maff-specification.html

**Comment by dougwilson** [comment]
Instructions on how to get new types added: https://github.com/jshttp/mime-db/blob/master/README.md#adding-custom-media-types :+1:

**Comment by danny0838** [comment]
Is there currently a protocol for what should be added to custom-types.json and what should not (and instead, be added after registered in IANA)?

**Comment by dougwilson** [comment]
The protocol is if at all possible nothing should be added there. It should be shrinking in size. It was mainly a mechanism to merge the existing data from the node-mime project and arguing about it is a lot of heart ache when this project should just be aggregating it's upstream sources.

**Comment by dougwilson** [comment]
Since this module doesn't source the compressible flag (a bad decision, in retrospect) it's the only definately permissible data to add to those files since it's currently the only way to add it.

**Comment by rmzelle** [comment]
So, should this mimetype be added to custom-types.json? I'd be happy to create a PR to add:

```
  "application/x-maff": {
    "compressible": false,
    "extensions": ["maff"],
    "sources": [
      "http://maf.mozdev.org/maff-specification.html",
      "https://en.wikipedia.org/wiki/Mozilla_Archive_Format"
    ]
  }
```

**Comment by dougwilson** [comment]
Hi @rmzelle the type / extension needs to get added to one of our upstreams: NGINX, Apache, or IANA.

**Comment by rmzelle** [comment]
In that case this issue can be closed, no?

**Comment by danny0838** [comment]
This issue is here for a year. Is there any plan that it should be implemented or not?

**Comment by dougwilson** [comment]
https://github.com/jshttp/mime-db/issues/115#issuecomment-393223425
