### ISSUE TITLE
mime type for .csv files can be reported incorrectly under specific conditions

### ISSUE THREAD

**Issue by ZuBB** [jshttp/mime-db#118]
By default mime type for `.csv` files should be `text/csv`. However in case when target OS is MS Windows and MS Office is also installed on that system mime type for that file will be `application/vnd.ms-excel`

I was able to reproduce this issue on Win 8 and Win 10 and latest MS Office. Also I have found few links where sames issue or issues based on this are discussed
* https://github.com/react-dropzone/react-dropzone/issues/276
* https://github.com/thoughtbot/paperclip/issues/1924#issuecomment-218141097
* https://bugs.chromium.org/p/chromium/issues/detail?id=139105
* https://answers.microsoft.com/en-us/msoffice/forum/msoffice_outlook/users-unable-to-open-attachments-even-after/3f326c89-6aec-49c5-9428-5160343d2450
* https://social.technet.microsoft.com/Forums/office/en-US/018b4d16-5fe7-4f95-b428-052332b358d8/excel-csv-file-enforce-mime-type?forum=excel

I do not know right way how we should go with this, but I am sure we need a place where all bits on this issue will be gathered together

**Comment by ZuBB** [comment]
I am going to make a quick check of this for Mac+MS Office

Also seems we will have a monkey patch for this on top of mime-db in our own repo..

**Comment by dougwilson** [comment]
This module is just a static JSON file. If you need logic like differing types based on running OS , then you need something on top of this module to do that :+1:
