### ISSUE TITLE
Adding Microsoft Smooth Streaming mime type

### ISSUE THREAD

**Issue by alias8** [jshttp/mime-db#131]
I noticed the .ism extension for a Microsoft Smooth Streaming file is not included. I cannot find it on the sites you aggregate from. 
http://www.iana.org/assignments/media-types/media-types.xhtml
http://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types
http://hg.nginx.org/nginx/raw-file/default/conf/mime.types

I believe the entry would be (with a correct source):

```
  "application/vnd.ms-sstr+xml": {
    "source": "???",
    "extensions": ["ism"]
  }
```

**Comment by Martii** [comment]
https://msdn.microsoft.com/en-us/library/jj573656%28v=vs.90%29.aspx most likely. Good luck in getting M$ to register their MIME types with the sources available.

**Comment by dougwilson** [comment]
Hi! Yes, this module just aggregates together those three sources so if that is not in any of the three it won't be in the aggregation here. You'll want to get it added in at least one of those places (IANA, Apache, or NGINX) if you're looking to see it appear here :+1:
