### ISSUE TITLE
Please add image/icns

### ISSUE THREAD

**Issue by aabfred** [jshttp/mime-db#135]
Missing  image/icns

**Comment by dougwilson** [comment]
This module aggregates data from the following sources:

http://www.iana.org/assignments/media-types/media-types.xhtml
http://svn.apache.org/repos/asf/httpd/httpd/trunk/docs/conf/mime.types
http://hg.nginx.org/nginx/raw-file/default/conf/mime.types

Just get it added to one of the above sources and we'll include it as part of the aggregate.
