### ISSUE TITLE
extension name `.ico`'s mime type changed

### ISSUE THREAD

**Issue by dead-horse** [jshttp/mime-db#140]
Looks like this extension conflict with extension for image/x-icon and change the value of mimeTypes.contentType('ico') from image/x-icon to image/vnd.microsoft.icon

https://github.com/jshttp/mime-db/commit/0dc5b639550046e9940c052c13e7926976e6b81a#r30314927

**Comment by dead-horse** [comment]
- https://github.com/favicon.ico => 'image-xicon'
- https://google.com/favicon.ico => 'image/x-icon'
- https://www.amazon.com/favicon.ico => 'image/x-icon'
- https://www.facebook.com/favicon.ico => 'image/png'
- https://www.microsoft.com/favicon.ico => 'image/x-icon'
- https://www.iana.org/favicon.ico => 'image/vnd.microsoft.icon'

I checked some big websites, most of them are still using `image/x-icon`, it won't effect any production servers but just break my test case, so I'm ok if you think this change is appropriate. :)

**Comment by dougwilson** [comment]
This module didn't change anything in this regard -- we still list image/x-icon can be .ico in the database.

**Comment by dead-horse** [comment]
yep, but https://github.com/jshttp/mime-types directly use mime-db's data, and `image/vnd.microsoft.icon` has higher priority for now, so `mimeTypes.lookup('.ico')` return `image/vnd.microsoft.icon` now.

**Comment by dougwilson** [comment]
Ok, but what would be the course of action this module can take? Remove the type data from our database? That doesn't seem right to me, especially since it reflects the registration in the IANA. What is the suggestion you're making for this module to do?

**Comment by dead-horse** [comment]
It's ok for me to keep this module not change, I'm just curious why my test cases failed.
