### ISSUE TITLE
Any chance of getting TS for TypeScript?

### ISSUE THREAD

**Issue by jeremyBanks** [jshttp/mime-db#148]
The `ts` file extension currently gets the MIME type `video/mp2t` from the "nginx media types" source. However, these days the extension is also frequently used for TypeScript source code. I was working on a post I was going to serve via GitHub Pages, and was disappointed to find out that when I linked to TypeScript files, expecting users to see the text source, the users were instead being prompted to download them due to this type. They are also frequently referenced via source maps.
 
Is there any chance that `ts` could have a custom `text/plain` entry instead?

**Comment by dougwilson** [comment]
So this module is just an aggregation of the sources listed in the README. The ts extension was of course used well before typescript existed, which is likely why it is coming through as something else, which is certainly a valid entry, as dvds and blu rays still are widely used and have files with .ts extensions.

So this database is a mapping of mime types and what extensions are known to be with them, not the the way around. Of course someone could be assuming the reverse from this module.

If whatever the mime is for typescript is added to this database with ts extension there will now be two mimes with ts extension unless the nginx project removes their mapping.

If the typescript mapping is added to any of our upstream sources it will automatically be added to this module. https://github.com/jshttp/mime-db/blob/master/README.md#adding-custom-media-types documents the public method to add to IANA for example.

You can name a pull request for a custom entry as well, but it'll only be accepted if there is a primary source included that associates the extension with the given mime type in the pr :+1:

I hope that helps and explains how to get that type into our aggregate database!
