### ISSUE TITLE
zip archive not supported

### ISSUE THREAD

**Issue by saeidjoker** [jshttp/mime-db#154]
please support application/x-zip-compressed.

**Comment by dougwilson** [comment]
Hi @saeidjoker , this module is an aggregate of the three sources listed at the top of the README (https://github.com/jshttp/mime-db#mime-db):

- Apache HTTPD
- NGINX
- IANA

Getting that type added to one of those three will result in us aggregating it into this project's database.

The IANA has the clearest path to get types added The community registration procedure is outlined in
[RFC 6838 section 5](http://tools.ietf.org/html/rfc6838#section-5). Types registered with the IANA are automatically pulled into this library.

You can also get it added to NGINX or Apache HTTPD as well.
