### ISSUE TITLE
Erro npm install v1.38.0 via npm

### ISSUE THREAD

**Issue by niccolascosta** [jshttp/mime-db#158]
npm ERR! code ETARGET
npm ERR! notarget No matching version found for mime-db@1.38.0
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/agriness/.npm/_logs/2019-03-11T12_31_38_075Z-debug.log

**Comment by dougwilson** [comment]
Are you using a mirror? What is the contents of that log file? The version is there on the npm, inc. registry, at least.

**Comment by dougwilson** [comment]
I'm going to close this since I never got a response.
