### ISSUE TITLE
font/woff for woff font

### ISSUE THREAD

**Issue by btd** [jshttp/mime-db#16]
Hi.

I havs small application that proxy pages (basically download pages and associated resources) and i noticed that some sites return woff fonts with `font/woff`, i did not notice this module has this content-type.

**Comment by dougwilson** [comment]
`.woff` is `application/font-woff`
`.woff2` is `application/font-woff2`

**Comment by dougwilson** [comment]
This is as per the `WOFF` font specification: http://www.w3.org/TR/WOFF/#appendix-b

**Comment by btd** [comment]
Yes, i know about `application/woff`, but you may know that e.g in early days it was `application/x-font-woff`. The same was with `font/woff`.
I agree that it is not a good option to add everything that developer come in mind, at least in this question will be all alternatives that i am adding for this font.

**Comment by dougwilson** [comment]
Gotcha. As far as what mime types we have, we don't keep a list here, we only pull it from the sources listed in the readme. If one of those sources adds other woff mimes, then we'll automatically pick it up.

**Comment by Fishrock123** [comment]
`font/woff` is invalid, there is no type namespace of `font/`.

Are there specific clients that require this? e.g. chrome gives warnings unless OpenType Fonts are served as `font/otf`.
