### ISSUE TITLE
Worth to add nginx mime.types

### ISSUE THREAD

**Issue by btd** [jshttp/mime-db#17]
You may know that nginx another wide popular proxy server, and it has own mime.types db.
That is nearest [link](https://github.com/git-mirror/nginx/blob/master/conf/mime.types). It is short but for some mime types it has additional extenisions.

**Comment by dougwilson** [comment]
Adding nginx sounds fine to me.

**Comment by dougwilson** [comment]
Ok, so I added this in a branch https://github.com/jshttp/mime-db/compare/nginx , but since it's adding even more duplicate file extensions, I think we really need to compile a source of ext-to-preferred-mime db before I can merge this.

**Comment by dougwilson** [comment]
This will land after #20 lands :)!

**Comment by dougwilson** [comment]
nginx types are not officially a source :)

**Comment by dougwilson** [comment]
nginx types are now officially a source :)
