### ISSUE TITLE
IPython notebooks extension support

### ISSUE THREAD

**Issue by dmvieira** [jshttp/mime-db#176]
We have no sources with this standard for ipynb extension: https://jupyter.readthedocs.io/en/latest/reference/mimetype.html

**Comment by dougwilson** [comment]
I don't see anything about a `.ipynb` file extension on that page?

**Comment by dmvieira** [comment]
I see that it's alread in [shared mime info](https://freedesktop.org/wiki/Software/shared-mime-info/) in this [line](https://gitlab.freedesktop.org/xdg/shared-mime-info/blob/master/freedesktop.org.xml.in#L2520). What do you think about include this source in mime-db?

**Comment by dougwilson** [comment]
This module only pulls from the three sources listed at the top of the readme. To pull it in, the best method is relly to get it into the IANA database.

**Comment by dougwilson** [comment]
As a stop gap measure, types can be added directly to this module, but you would need to find a primary source so I can vet it. Sites that are just aggregate mime types are a secondary source. So if you can find out where that site sourced the data from for this mapping that should work.

**Comment by flying-sheep** [comment]
Well, that’s a mirror of freedesktop’s “[shared mime info](https://freedesktop.org/wiki/Software/shared-mime-info/)” list. freedesktop is an initiative for interoperability in *NIXoids, to which end they define standards. They aren’t an official standards body, but followed by all bigger desktop environments on Linux like GNOME and KDE Plasma.

I consider a DB compiled by them second to IANA, and much more official than any specific server software’s collection. So if you aggregate from nginx and Apache, you should definitely also aggregate from freedesktop’s shared-mime-info.

**Comment by dougwilson** [comment]
If we were to add that as a source, where is the shared mime info list hosted for us to pull from it directly? Do they have any policy against automated pulling of their data?

**Comment by flying-sheep** [comment]
On the linked page are “[Sources](https://gitlab.freedesktop.org/xdg/shared-mime-info/)” and “[Releases](https://gitlab.freedesktop.org/xdg/shared-mime-info/-/releases)”, both linking to their GitLab instance. Linux distros [like e.g. Arch pull](https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/shared-mime-info) from there.

**Comment by dougwilson** [comment]
I'm going to close this as it has been a few years and it is still neither (a) registered with IANA nor (b) just clarified on their own documentation what file extension for what MIME type. If the project is not interested in even documenting it on their own site, it would seem they don't want the association known, and so won't be included here without at least one of those being done.

**Comment by julien-c** [comment]
FYI, following up with a narrower-scoped proposed solution to this in #282
