### ISSUE TITLE
Add extension .jfif to image/jpeg

### ISSUE THREAD

**Issue by GustavoMilitao** [jshttp/mime-db#177]
The "jfif" is an image extension. See the link below. 

https://www.w3.org/Graphics/JPEG

**Comment by dougwilson** [comment]
Without a link from a primary source that clearly states the file extension .jfif exists and belongs to image/jpeg mime, you would need to follow the process as described in https://github.com/jshttp/mime-db/blob/master/README.md#adding-custom-media-types

The link provided has no mention of a file extension of any kind, so there is no way to know from that link that ".jfif" is even a valid file extension.

The linked IANA process can help step though the process to gather the needed data. Ultimately, this module is a JSON representation of the IANA database.

**Comment by jayesh-solutelabs** [comment]
@GustavoMilitao Is there any follow ups on this issue ?

**Comment by harrycollin** [comment]
> 

is this still the case?

**Comment by ajeyacube** [comment]
@dougwilson We are also facing the same issue with jfif extension. Are there any update?
