### ISSUE TITLE
Require 2FA for JSHttp members?

### ISSUE THREAD

**Issue by broofa** [jshttp/mime-db#179]
[This isn't a mime-db issue, but I'm not sure how else to communicate with the JSHttp admin crew.  Please direct me to a more appropriate forum if one exists.  (E.g. perhaps there could be a "meta" repository managing JSHttp-related docs and business that aren't specific to a single repo?  Not sure if there's a need for that.]

Briefly, I'll suggest that [2FA authentication should be required](https://help.github.com/en/github/setting-up-and-managing-organizations-and-teams/requiring-two-factor-authentication-in-your-organization) for JSHttp members.  This will help protect the integrity of several projects that are depended upon by, literally, millions of other projects.

**Comment by dougwilson** [comment]
> E.g. perhaps there could be a "meta" repository managing JSHttp-related docs and business that aren't specific to a single repo?

https://github.com/jshttp/jshttp.github.io/issues

**Comment by dougwilson** [comment]
The jshttp org itself also falls under the Express TC, so https://github.com/expressjs/discussions is another avenue.

**Comment by dougwilson** [comment]
> This will help protect the integrity of several projects that are depended upon by, literally, millions of other projects.

This part isn't 100% clear to me, as I assume we are talking about npm modules here and publishing to npm and pushing yo github are different systems, so enabling 2FA in github won't do anything to ensure integrity of the npm package. It would, I understand, ensure it if folks are pulling direct from npm and not from github.

I enabled 2FA as a github requirement now, though, fwiw.
