### ISSUE TITLE
@1.43.0 was not published successfully

### ISSUE THREAD

**Issue by YeatsLu** [jshttp/mime-db#182]
@1.43.0 is not found at npm repo, maby npm publishing is failed

there is issue of "npm isntall" at a project by create-react-app

**npm dependences chains:**
react-scripts -> webpack-dev-server -> compressible -> mine-db

**Comment by viditpandey** [comment]
Hi,
We are also facing this issue in our project. The build is failing with error log: **"No matching version found for mime-db@>= 1.43.0 < 2"**

**Comment by Gauri-P** [comment]
We are also facing exact same issue. Please provide the fix as our builds are failing.

**Comment by dougwilson** [comment]
Neither I, nor Travis CI, is having an issue installing from npm registry. Please check if you are using a mirror, otherwise contact npm support.

**Comment by ffinki** [comment]
Also here... the same issue

**Comment by YeatsLu** [comment]
@dougwilson [get it](https://www.npmjs.com/package/mime-db) 
> Please check if you are using a mirror, otherwise contact npm support.
