### ISSUE TITLE
Add common name?

### ISSUE THREAD

**Issue by metaraine** [jshttp/mime-db#19]
Thoughts about adding a property like `commonName` that provides a short, commonly used label for certain types?

e.g.
text/calendar is commonly known as iCalendar.

This is coming up for me because I am building an app that displays file types as a dropdown list for end users.

**Comment by dougwilson** [comment]
That's fine as long as we can source it from somewhere and not have to add it manually to every single type.

**Comment by dougwilson** [comment]
This is what the registration on the IANA looks like for `text/calendar`: http://www.iana.org/assignments/media-types/text/calendar

**Comment by jonathanong** [comment]
another example is `urlencoded` - `application/x-www-form-urlencoded` (maybe `form` as well)

**Comment by metaraine** [comment]
Most mime-types can just use what's after the `/`, without `x-` or `vnd`, as a user-friendly name. There are just a few like iCalendar that are different and indeterminable from the type alone. I feel like manually adding it to those few wouldn't be too hard. 

Maybe it's not worth it though and it's easier to just map friendly names in-application or in a small separate module.

**Comment by dougwilson** [comment]
If we need to have some hand-rolled values that's fine, but I'll probably have to accept it as a PR, if you're so inclined. Right now we have 1,787 mime types listed. Really, to add a new data point, I would except at least 75% of them have the data point. If we can generate them in a way where they _always_ make sense (and if they don't, then the generator needs to just leave the field null), then that would work and we can add in a hand-rolled data set of the few that cannot be determined correctly.

**Comment by dougwilson** [comment]
For example, you probably have to hand roll `application/vnd.openxmlformats-officedocument.presentationml.presentation`, since that is the MIME type for "PowerPoint Presentation", and doesn't seem determinable from the type itself.

**Comment by metaraine** [comment]
Good points. I will think about this.

**Comment by dougwilson** [comment]
So I'm going to close this due to lack of activity; I haven't thought of anything in the meantime, but if you do, let me know and I can always reopen :)

**Comment by metaraine** [comment]
K, will do ;)
