### ISSUE TITLE
Invalid mime type for .map

### ISSUE THREAD

**Issue by sfrylmark** [jshttp/mime-db#190]
[This commit](https://github.com/jshttp/mime-db/commit/129996a4e437e33bcad8e488c48fb191671fe158#diff-a23d66d6c3d5a521d8fb16ef6b45488eR9) bound `.map` to `application/json`.

There's no standard for this. [Wikipedia](https://en.wikipedia.org/wiki/MAP_(file_format)) names a number of different uses for the `.map` file extension, for example [HTML Image Maps](https://en.wikipedia.org/wiki/Image_map), as used in some versions of Doxygen.

This breaks my flow. If possible, please make it more specific like if the files end with `.json.map` or something. Otherwise, removing the mapping in `custom-types.json` would probably be good.

EDIT: Updated the commit, thanks!

**Comment by dougwilson** [comment]
It looks like the commit that brought thins binding into thia module is https://github.com/jshttp/mime-db/commit/129996a4e437e33bcad8e488c48fb191671fe158

**Comment by efrlsml** [comment]
Thanks for correcting!

**Comment by dougwilson** [comment]
So it looks like this came from the javascript source map type. A javascript source map is a file that ends in .map and is json.

**Comment by efrlsml** [comment]
I figured. But isn't that always `.js.map` instead of just `.map`? For such a generic name as "map" it is probably bad to start generalizing extensions that aren't standard anywhere.

**Comment by broofa** [comment]
Interesting issue.  I'm inclined to agree with @efrlsml that mapping such a generic extension to a JS-specific type without any formal standard may be problematic in the future.

Scoping this to ".js.map" extensions is probably the right solution, however that will be problematic for modules such as `mime` and `mime-types`  (and probably other downstream consumers) that don't expect compound extensions such as ".js.map". See also:

* https://github.com/broofa/mime/blob/master/Mime.js#L76-L85
* https://nodejs.org/api/path.html#path_path_extname_path (used by `mime`)

As the maintainer of `mime`, I'll say that adding support for compound extensions is probably trickier than it seems.  Lots of cases that may result in unexpected behavior.  (e.g. a file named "js.map" -> `application/json`, but "other.map" -> (some other type))

**Comment by dougwilson** [comment]
Yea, we pulled in a lot of strange mappings like this one from the node-mime lib. I have been working to remove all these custom mappings from this db, as it creates an easy way for this module to be in arguments about what is right or wrong mappings.

The future is the continued removal of all custom types and push towards this being an aggregation of sources, where disputes can take place at those sources which have the processes and folks to handle them (like the IANA).

**Comment by mastermatt** [comment]
@dougwilson I'm attempting to label this issue given it's current state. Are we looking for PRs to remove `.map`?

**Comment by dougwilson** [comment]
I think the general discussion has mostly ended now, as the original has been identified.
