### ISSUE TITLE
People creating aliases of mime-db for Deno by fetching the db.json directly

### ISSUE THREAD

**Issue by Swap76** [jshttp/mime-db#195]
I know as per the opensource license this is allowed but have look https://github.com/alirealasad/mine_db/blob/master/mod.ts

<img width="1008" alt="Screenshot 2020-05-28 at 4 02 26 AM" src="https://user-images.githubusercontent.com/37082605/83078817-0f46e900-a098-11ea-883c-62b28e6b38ce.png">

The PR for this repo to be included in the third-party module is created on the Deno website

This is ripping off all the work people have put up for years

**Comment by dougwilson** [comment]
Thanks, but I'm not sure there is anything wrong there. We allow downloading the db directly (see https://github.com/jshttp/mime-db/blob/master/README.md#database-download). At best, pulling from github may be against the github tos depending on where/for what purpose they are doing it for.

**Comment by jonchurch** [comment]
FWIW they are crediting this project in their readme.

**Comment by Swap76** [comment]
@jonchurch Sorry guys my bad ...
