### ISSUE TITLE
Support for obj and mtl

### ISSUE THREAD

**Issue by jaider** [jshttp/mime-db#197]
I am surprise these MIME Types used for 3D objects are not supported by default.

**Comment by dougwilson** [comment]
Very strange. This module pulls data from the three sources at the top of the READMEhttps://github.com/jshttp/mime-db/blob/master/README.md#mime-db so I guess those are not in there or something else is wrong. What are the mime types for those extensions?

**Comment by helio-frota** [comment]
hi @jaider 

I think the issue can be closed, these mime types are already supported.

https://github.com/jshttp/mime-db/search?q=model/mtl
https://github.com/jshttp/mime-db/search?q=model/obj

```console
[.~/code/foo] cat a.js 
var m = require('mime-types')
console.log(m.lookup('mtl'))
console.log(m.lookup('obj'))

[.~/code/foo] node a.js 
model/mtl
model/obj

[.~/code/foo] rg mtl node_modules/mime-db/db.json 
7237:  "model/mtl": {
7239:    "extensions": ["mtl"]
```

https://www.iana.org/assignments/media-types/model/mtl
https://www.iana.org/assignments/media-types/model/obj
