### ISSUE TITLE
Script isn't extract .rar extension from IANA primary source

### ISSUE THREAD

**Issue by belsholff** [jshttp/mime-db#206]
Checking an application error that use this module, I reach a problem with `application/vnd.rar` mime-type (WinRAR file mime-type), that has not an associated extension in `db.json`.

Checking the [primary source URL](https://www.iana.org/assignments/media-types/application/vnd.rar) indicated in `src/iana-types.json`, there is an extension declared (`.rar`). Maybe it could be a bug.

I cloned this module an tested some things:

1. extension extraction is working when manually called the function `extractTemplateExtensions(body)` before [line 131](https://github.com/jshttp/mime-db/blob/9194cf760317ec03daa104d751f446ddea22e788/scripts/fetch-iana.js#L131) of `scripts/fetch-iana.js`

2. `opts.extensions === true` and `opts.extensions.test(data.mime)` should be `false` in [line 129](https://github.com/jshttp/mime-db/blob/9194cf760317ec03daa104d751f446ddea22e788/scripts/fetch-iana.js#L129) at same file from 1? This verification breaks the flow where `extractTemplateExtensions(body)` could be called.

At this time I can't get this fixed without mainainer's help and submit a pull request. Sorry.

I Accept any suggestions about how report an issue. I'm new in Github world. :smile: 

thx

**Comment by dougwilson** [comment]
Hi @belsholff thanks for the notice! I just landed a commit adding this associate for you. I'll have it released as a new version soon.
