### ISSUE TITLE
"application/vnd.xmind.workbook" not exists

### ISSUE THREAD

**Issue by ZOUJIELynn** [jshttp/mime-db#208]
"application/vnd.xmind.workbook" not exists in mime json

**Comment by dougwilson** [comment]
Hi @ZOUJIELynn this is because it does not exist in any of the three upstream databases we pull from. If you would like to see it added, you're welcome to follow our section regarding getting a mime type added: https://github.com/jshttp/mime-db#adding-custom-media-types
