### ISSUE TITLE
Add TSX

### ISSUE THREAD

**Issue by vincaslt** [jshttp/mime-db#211]
Typescript with jsx files usually have extension `.tsx` which is missing here.

**Comment by dougwilson** [comment]
Thanks for the information 👍 . There are two paths forward here if you want to see this in the database:

1. Get the association added in one of the databases we source from: https://github.com/jshttp/mime-db#adding-custom-media-types
2. Make a PR according to https://github.com/jshttp/mime-db#contributing providing a primary source that shows the MIME type to extension association you are seeking to add
