### ISSUE TITLE
Types based off filename

### ISSUE THREAD

**Issue by jacobp100** [jshttp/mime-db#215]
Some specifications (official or otherwise) have special file names rather than extensions. For example `apple-app-site-association` is a JSON file, `.env` is a config file, `Fastfile` is a Ruby file.

The first one is a bit of a pain, because it makes it impossible to use GitHub Pages for an iOS app that wants to support universal links.

Would you consider supporting these special cases?

**Comment by dougwilson** [comment]
Hello! Can you talk about what would be the changes in this module needed for support these? All this module is is a list of mime types and what some properties are about that mime type, like the list of file extensions.

If you're looking to add `.env` extension or similar, you can find the instructions for how to contribute this at https://github.com/jshttp/mime-db#contributing
