### ISSUE TITLE
m4s is not mapped to video/iso.segment

### ISSUE THREAD

**Issue by kevinGodell** [jshttp/mime-db#216]
It seems that the `.m4s` extension is not mapped to `video/iso.segment`. The extension is mentioned in the [iana docs for video/iso.segment](http://www.iana.org/assignments/media-types/video/iso.segment) and also at [apple for HLS authoring](https://developer.apple.com/documentation/http_live_streaming/hls_authoring_specification_for_apple_devices#3314597).

**Comment by dougwilson** [comment]
Thanks for the report @kevinGodell . It is now pulling the extension from IANA.
