### ISSUE TITLE
.wav files show up as "audio/x-wav" instead of "audio/wav"

### ISSUE THREAD

**Issue by LorenzGardner** [jshttp/mime-db#22]
when setting the mime type for .wav files internet explore is a bit picky...

valid options are: audio/wav, audio/wave, audio/x-wave, audio/vnd.wave

Chrome happily accepts the "audio/x-wav" but IE does not.

See: broofa/node-mime#118

As broofa points out, "audio/wav" is the official type according to the IANA Waveform Audio File Format registration.
 http://tools.ietf.org/html/draft-ema-vpim-wav-00

**Comment by dougwilson** [comment]
Ah, yes. This is coming from Apache, which is (currently) our only source of file extensions. I will need to complete #20 before we can actually have the ability to override the Apache types.

**Comment by dougwilson** [comment]
So that references RFC is a draft, so it's not very useful. Apparently it ended up officially becoming `audio/vnd.wave` in http://tools.ietf.org/html/rfc2361 , but looking around all over the place, it seems like the best choice for us may be to use `audio/wav`. I haven't determined the reason Apache is using `audio/x-wav` yet, though.

**Comment by HughP** [comment]
> So that references RFC is a draft, so it's not very useful. Apparently it ended up officially becoming `audio/vnd.wave` in http://tools.ietf.org/html/rfc2361 , but looking around all over the place, it seems like the best choice for us may be to use `audio/wav`. I haven't determined the reason Apache is using `audio/x-wav` yet, though.

Actually, that link to RFC2361 is also to a draft. The MIME type for wave was never officially set. It doesn't appear in the official list.  https://www.iana.org/assignments/media-types/media-types.xhtml#audio Browsers do what is best for those who write them. the prefix 'x-' means that it is in the private use area.
