### ISSUE TITLE
Newline-delimited JSON

### ISSUE THREAD

**Issue by felipeochoa** [jshttp/mime-db#224]
There seems to be growing consensus[1][2] around using `application/x-ndjson` for [newline-delimited JSON](https://github.com/ndjson/ndjson-spec), which is used for streaming JSON objects. There isn't an RFC yet for ndjson[3], which I think precludes registering with IANA. Would it be possible to nonetheless add to this library as a 'custom' MIME type?

1: [Elasticsearch](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/docs-bulk.html)
2: [Spring Framework](https://github.com/spring-projects/spring-framework/issues/21283#issuecomment-665114578)
3: ndjson/ndjson-spec#21

**Comment by dougwilson** [comment]
Hi @felipeochoa ! An RFC is not required to submit the IANA form, as far as I know. Can you link to where you are seeing that an RFC of the format is required to add something to the IANA registry?

**Comment by dougwilson** [comment]
AFAIK it is just submitting the following form: https://www.iana.org/form/media-types

There are a lot of things in the IANA database (even recent ones I've seen come through) that have no RFC for their spec, especially private types like things companies define.

**Comment by mattbishop** [comment]
Just adding a +1 to this request.
