### ISSUE TITLE
Add jsm extension for application/javascript

### ISSUE THREAD

**Issue by khalyomede** [jshttp/mime-db#235]
## Descrption

I want my ".jsm" files to have the content-type "application/javascript". For the moment, I need to patch my Express server manually to add this mapping.

## Expected behavior

The extension ".jsm" is associated to the "application/javascript" MIME type.

**Comment by dougwilson** [comment]
Hi @khalyomede thanks for this issue. Please note that this project is an aggregation of the three sources listed at the top. If this association is missing from those sources, it wouldn't be included here. If you think it should and don't want to pursue getting it added to one of our sources, you can follow the guidelines listed at https://github.com/jshttp/mime-db#contributing

**Comment by younggun23** [comment]
https://github.com/younggun23/mime-db

**Comment by younggun23** [comment]
https://github.com/younggun23/mime-db
