### ISSUE TITLE
Magic numbers

### ISSUE THREAD

**Issue by gchudnov** [jshttp/mime-db#24]
Are there any plans to add magic number support to deduce the mime-type for a Buffer?
e.g. "ff d8 ff e0" for "image/jpeg"

**Comment by Fishrock123** [comment]
No, that is well beyond the scope of this library. jpegs should already have been labeled as `image/jpeg`.

[mmmagic](https://www.npmjs.com/package/mmmagic) does byte sniffing for types, however.

**Comment by dougwilson** [comment]
We could potentially add what the magic numbers are to our database, but they aren't very useful. The `mmmagic` library, as @Fishrock123 pointed to, is really better than we could ever do; some types you pretty much have to fully parse the file to detect (looking at you, MP3).

**Comment by gchudnov** [comment]
That's right, but it doesn't work in the browser. You have to upload file to the server to use it.
But I see your point.

**Comment by jonathanong** [comment]
https://github.com/sindresorhus/is-jpg

there are a lot of these as tiny modules on npm. there are a lot!
