### ISSUE TITLE
'.zip' file has a 'application/x-zip-compressed' in Windows.

### ISSUE THREAD

**Issue by yrm006** [jshttp/mime-db#245]
In the Windows, '.zip' file has a contentType 'application/x-zip-compressed'.

Please consider adding 'application/x-zip-compressed' to db.

Thank you,

**Comment by dougwilson** [comment]
Hello, and thank you for the suggestion. This module is an aggregation of the three sources listed at the top of the README (Apache, NGINX, and IANA). The IANA has a standard process to add new mime types and this project will pull it in automatically. You can find the process at https://github.com/jshttp/mime-db#adding-custom-media-types

**Comment by yrm006** [comment]
Thank you, I will do that.
