### ISSUE TITLE
Latest version :

### ISSUE THREAD

**Issue by wasimEnayathulla** [jshttp/mime-db#251]
I am not able to install the latest version.  1.51.0
![Screenshot from 2021-11-09 18-23-41](https://user-images.githubusercontent.com/87307047/140928048-56db9ad5-b306-4236-b8f9-08b6669cb246.png)

**Comment by dougwilson** [comment]
Sorry you are having troubles with npm. You will need to contact npm, as there is nothing more I can do frok my end, as it is published.
