### ISSUE TITLE
.asc extension maps to application/pgp-signature instead of application/pgp-keys

### ISSUE THREAD

**Issue by kusma** [jshttp/mime-db#256]
According to IANA, [PGP keys](https://www.iana.org/assignments/media-types/application/pgp-keys) only have one extension, `.asc`. However, [PGP signatures](www.iana.org/assignments/media-types/application/pgp-signature) can either have `.asc` or `.sig`.

The likely reason for `.asc` being used for both this is that the extension comes from the "ASCII-armored" concept rather than what the usage of the armored content.

This database seems to somewhat arbitrarily assign that extension only to `application/pgp-signature` instead of both. This is a bit unfortunate, because it makes it impossible to get the right MIME type for PGP keys, based on filename matching.

I realize that this isn't a case where we can really please everyone. But it seems more useful to assign this one to the PGP keys, because there's an alternative (and seemingly more widely used) extension for PGP signatures; `.sig`.

**Comment by dougwilson** [comment]
Thanks for the report. This module aggregates from the three sources listed at the top of the readme. I will look why the IANA one is not getting pulled. The current one comes from Apache, so if you don't think that is right, you will need to bring that up with the Apache project to correct.
