### ISSUE TITLE
'cogent' is breaking builds on SSH Git protocol

### ISSUE THREAD

**Issue by d-stew** [jshttp/mime-db#257]
The `cogent` dependency is using unencryted Git protocol, which breaks builds on SSH as DSA keys are no longer supported.

See: https://github.blog/2021-09-01-improving-git-protocol-security-github/

It seems `cogent` is no longer actively maintained. Is it possible to find an alternative for this package?

**Comment by dougwilson** [comment]
It's just a devDependency, so doesn't matter to anyone using the module itself, and low priority for me. If you would like to make a pull request to change it to something else, please do! I have been wanting for a long time, but it seemed like a big, low priority task so I never did yet, lol.

**Comment by dougwilson** [comment]
FWIW every dependency of `cogent` is an npm reference, no git references:
```
$ npm info cogent@1.0.1 dependencies
 
{ debug: '*',
  netrc: '~0.1.3',
  'write-to': '^1.0.0',
  'raw-body': '^1.1.2',
  statuses: '^1.0.2' }
```

**Comment by dougwilson** [comment]
I just installed everything afresh and didn't have any failures, nor can I find anything thay actually uses the unencrypted Git procol has claimed, so idk if there is any quick fix, as I cannot replicate any issue.
