### ISSUE TITLE
TypeScript file extensions map to incorrect file types

### ISSUE THREAD

**Issue by zsakowitz** [jshttp/mime-db#259]
Currently, `.ts` maps to `video/mp2t`, `.mts` maps to `model/vnd.mts`, and `.tsx` and `.cts` aren't in the database.

TypeScript uses these extensions:
- `.ts` is a standard TypeScript file (currently `video/mp2t`, should be `text/typescript`)
- `.tsx` is a TypeScript + JSX file (should be `text/tsx`)
- `.mts` compiles to a `.mjs` file and always runs as an ES module (currently `model/vnd.mts`, should be `text/typescript`)
- `.cts` compiles to a `.cjs` file and always runs as a CommonJS module (should be `text/typescript`)

I think that modifying these would be helpful to the user base and fix issues with static file servers thinking TypeScript files are videos. It would also be nice if `.ts` could both be `video/mp2t` and `text/typescript`, but I'm not sure what the opinion is on that.

**Comment by dougwilson** [comment]
Hi @zsakowitz and thank you for your issue. This module only provides a list of mime types that has a property of extensions associated with that mime type. You can find the list of where the data is sourced from in the README and instructions for how to get a new mime type (and thus extensions) added. Please check out https://github.com/jshttp/mime-db#contributing
