### ISSUE TITLE
Webjar 1.52.0 version

### ISSUE THREAD

**Issue by Flaurite** [jshttp/mime-db#260]
### Description
Could you please release the new 1.52.0 webjar version?
https://www.webjars.org/

**Comment by dougwilson** [comment]
Hello, I have no idea what that is, nor how to release any version. This is just a Node.js module I publish on npm.

**Comment by dougwilson** [comment]
As far as I can tell from looking at the website and stuff, there is no way I could publish it there, anyway. It seems designed to automatically mirror npm. You likely need to open an issue with the project to help them determine what is wrong with their mirroring.

**Comment by Flaurite** [comment]
Thank you for the hint! It seems the webjars.org can automatically detect the new module version. I just added 1.52.0 version by clicking plus button and choosing NPM webjar type.
