### ISSUE TITLE
More type mappings

### ISSUE THREAD

**Issue by jonnyfux** [jshttp/mime-db#261]
I suggest four additions that are currently missing

1. .properties => text/plain ; **Reason**: Used by Ubuntu
2. bcmap => application/octet-stream **Reason**: Used by Ubuntu, and [here](https://www.filesuffix.com/de/extension/bcmap#ext0)
3. gltf => text/plain ; **Reason**: Used by Ubuntu
4. map => text/plain ; **Reason**: Used by Ubuntu

**Comment by dougwilson** [comment]
Hello, and thank you for your suggestions. You can find instructions for contributing in the readme: https://github.com/jshttp/mime-db#contributing
