### ISSUE TITLE
audio/x-flac -> audio/flac

### ISSUE THREAD

**Issue by kleydon** [jshttp/mime-db#277]
In mime-db/db.json:
```
"audio/x-flac": {
    "source": "apache",
    "extensions": ["flac"]
},
```

* According to the Mozilla Developer Network (MDN) [here](https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Containers#flac), `audio/x-flac` is non-standard, while `audio/flac` is standard.

* Xiph, which created the flac format, lists the mime-type as `audio/flac` [here](https://wiki.xiph.org/MIME_Types_and_File_Extensions).

* The [mimetype site](https://mimetype.io/audio/x-flac) additionally describes `x-flac` as "depreciated" in favor of `audio/flac`

* Looking at the behavior of 3 common desktop browsers, when you navigate to a url that is a `.flac` file...

>>Chrome: 
`audio/x-flac` - Doesn't show a player; just downloads the file
`audio/flac` - Shows an audio player, plays the file in a browser window

>>FireFox: 
`audio/x-flac` - Shows an audio player, plays the file in a browser window
`audio/flac` - Shows an audio player, plays the file in a browser window

>>Safari:
`audio/x-flac` - Doesn't show a player; just downloads the file
`audio/flac` - Shows an audio player (which unfortunately doesn't play the file, as of 11/2022)

**Comment by dougwilson** [comment]
Hi @kleydon and thank you for your issue. The entry you are pointing to is just showing the data the Apache project has. This project takes from the three sources listed at the top of the readme, like the Apache one listed. If you think that the Apache entry should be changed, you'll want to raise an issue with the Apache project so they can change it. Any changes will be pulled in to our database automatically.

**Comment by kleydon** [comment]
Ah - got it.
