### ISSUE TITLE
Missing file extension .SRW

### ISSUE THREAD

**Issue by samip5** [jshttp/mime-db#280]
It seems that the database is missing a mimetype for the following file extension.

The MIME Type as parsed by exiftool is `image/x-samsung-srw`

This is Samsung's raw picture format.

**Comment by dougwilson** [comment]
Hello, and thank you for letting us know! Instructions for how to add missing types and extensions, please follow the steps in the README: https://github.com/jshttp/mime-db#registering-media-types
