### ISSUE TITLE
Suggestion: add perceived type

### ISSUE THREAD

**Issue by thany** [jshttp/mime-db#4]
Friendly suggestion to add perceived type to each mime type. This would make it easier to distinguish between types of media such as video, audio, graphics, text, etc. The first part of a mime type is not always the deciding factor, after all. Plus there are agnostic mime groups, like application.

Perhaps perceived type could be left out when the mime group makes it clear by itself.

**Comment by dougwilson** [comment]
So I looked really hard into this, and though it sounds nice to have, the way it actually works in Windows is part of the type registration (which lives in the registry). Applications can alter these types at will and there is pretty much no central place for these things to exist. It basically seems like making this would be completely hand-rolled, which seems like a large task.

It is certainly possible that we can write a script that will simply walk the registry of the current user and store all those perceived types, though it will still end up being a manually-curated list of them :)
