### ISSUE TITLE
Dynamic adaptive streaming over HTTP (DASH) file extension typo?

### ISSUE THREAD

**Issue by mruddy** [jshttp/mime-db#44]
https://www.iana.org/assignments/media-types/application/dash+xml
application/dash+xml is registered for file extension "mpd", not "mdp".
related standard ISO/IEC 23009-1:2014

master currently references "mdp" in two places that i saw:
https://github.com/jshttp/mime-db/blob/master/db.json#L220
https://github.com/jshttp/mime-db/blob/master/src/custom-types.json#L21

**Comment by dougwilson** [comment]
Looks like when we merged in the `mime` project into this module, that's where it came from: https://github.com/jshttp/mime-db/commit/129996a4e437e33bcad8e488c48fb191671fe158

Probably just a simple typo, which we would be glad to fix :)!

**Comment by mruddy** [comment]
looks good, thanks!
