### ISSUE TITLE
Provisional Standard Media Type Registry

### ISSUE THREAD

**Issue by Martii** [jshttp/mime-db#47]
Hi there. Thanks for this great project.

I did have a question however. Currently `image/jxr` is sitting in "limbo" at [IANA](http://www.iana.org/assignments/provisional-standard-media-types/provisional-standard-media-types.xhtml) however it is actively being used in Windows 10 Edge browsers. Our site has received a few of these requests already.

It is also my understanding that the `.jxr` extension Media Type _(MIME for us more tenured folks)_ used to be `image/vnd.ms-photo` from a few reads throughout the internet.

My questions are fairly simple... are those PSMTR entries considered when making the database? Should they be?

Thanks so much.

**Comment by dougwilson** [comment]
Hm, that is a good question, and one that I have not thought of before. The description for what that is for says the following:

> Entries in this registry are suitable for use for development and test purposes only.

Through, of course, in practice it may be used differently :) The `image/jxr` issue can of course be resolved for now by making a pull request adding it to the custom types section, which is mixed into everything, but of course that would be something in parallel with this question :)

**Comment by dougwilson** [comment]
Hi @Martii I'm going to close this issue, but please feel free to make PR to add the type to the custom types file :)
