### ISSUE TITLE
Add 'audio/x-vorbis' mime types

### ISSUE THREAD

**Issue by Alcotana** [jshttp/mime-db#52]
`audio/x-vorbis`, `audio/x-vorbis+ogg` ← `ogg`

PR #53

**Comment by Alcotana** [comment]
Sorry, it is supported. Remove this issue.

**Comment by dougwilson** [comment]
Hi @Alcotana I'm' not sure what happened, but your link leads to "We went looking everywhere, but couldn’t find those commits."

**Comment by Martii** [comment]
@dougwilson 
Contact support as the page it pulls in references issue #51 which doesn't appear to be related. Also @Alcotana's [history](https://github.com/Alcotana?tab=overview&from=2016-09-01&to=2016-09-30&utf8=%E2%9C%93) doesn't show any PRs/commits right now like the rest of us.

**Comment by Martii** [comment]
And now it shows a repo commit. heh... seems like a GH issue for support.

**Comment by Alcotana** [comment]
Yeah, the link is broken because I dropped the commit from the branch. The commit got into PR #51, which is about 'wav' files. I created another PR about 'ogg': #53

**Comment by dougwilson** [comment]
Closing from the conversation in #53
