### ISSUE TITLE
Mime type for .tar.gz and .tgz?

### ISSUE THREAD

**Issue by alolis** [jshttp/mime-db#62]
Hello,

I was wondering if the mentioned file extensions are going to be supported at some point. After checking around the recommended mime type for them is `application/gzip` but I might be wrong.

Looking forward to any feedback

**Comment by dougwilson** [comment]
Hi @alolis this project is just aggregating different sources. The best way to get them added it to get them added to one of the downstream sources, like the Apache or NGINX projects, and then we'll automatically pull the definitions in.

**Comment by KaKi87** [comment]
Hello,

> The best way to get them added it to get them added to one of the downstream sources, like the Apache or NGINX projects, and then we'll automatically pull the definitions in.

How is this going ?

Thanks
