### ISSUE TITLE
Move jpg to the first index of image/jpeg extensions array

### ISSUE THREAD

**Issue by darsain** [jshttp/mime-db#63]
Before:
```js
  "image/jpeg": {
    "extensions": ["jpeg","jpg"]
  },
```

After:
```js
  "image/jpeg": {
    "extensions": ["jpg","jpeg"]
  },
```

Why?

`mime-types` module has an `.extension(type)` method that returns first extension in this array, which is the horrible and ugly `jpeg` that none prefers over `jpg`, so I always have to do:

```js
let ext = mime.extension(type);
if (ext === 'jpeg') ext = 'jpg';
```

Or modify the `extensions` array at the start of my app (effectively detaching it from the affected code), than forgetting I did that, move to another project, and have to debug why are my files `.jpeg`s again.

In general it would be great to move the preferred extension in each `extensions` array to its 1st index. But this one is the one that will solve 99% of the frustrating "not a preferred extension" encounters.

It's just another one of those paper cuts that kill the joy of programming.

**Comment by dougwilson** [comment]
This project is just an aggregation of the sources listed in the README. It does already list the extensions with the most preferred as the first element. It looks like both the Apache and NGINX projects want to prefer the use of the jpeg extension, so I think the best course of action is to bring it up in those projects and we'll automatically pull down any change made upstream.
