### ISSUE TITLE
Issue in loading WOFF fonts in Express JS

### ISSUE THREAD

**Issue by JigneshRaval** [jshttp/mime-db#64]
Hi,

I was facing issue in loading WOFF fonts while using Ionicons icon-font in my Express.js + Node application.

After some investigation I have found that either we need to update or add new entry for WOFF fonts in DB.json file as given below at line no 370.

`application/x-font-woff`

db.json line no 370:  ` "application/x-font-woff" ` 

Ref URL : [http://stackoverflow.com/questions/3594823/mime-type-for-woff-fonts](http://stackoverflow.com/questions/3594823/mime-type-for-woff-fonts)

I hope this will be helpful.

Thanks,
Jignesh Raval

**Comment by dougwilson** [comment]
Hi @JigneshRaval this module aggregates from the sources listed in the readme. The `.woff` extension is mapped to `application/font-woff`, the official type by the Apache project. If they change the mapping, we'll automatically pull it in :)

**Comment by dougwilson** [comment]
In the Stackoverflow post you linked it, it says as of 2012, Chrome expects `application/font-woff`, not `application/x-font-woff`. The `application/font-woff` is what we have, so I'm not sure what is happening to you unless you're using a pre-2012 Chrome. Also, I don't think this module is in the dependency tree for Express currently, so not sure if a change here will make a direct difference there.
