### ISSUE TITLE
more types

### ISSUE THREAD

**Issue by jonathanong** [jshttp/mime-db#7]
https://github.com/jshttp/mime-types/issues/4

**Comment by dougwilson** [comment]
I'm closing this issue, as it's more of a call to contribute that belongs in the readme rather than an endless issue. We do have https://github.com/jshttp/mime-db#contributing

**Comment by NaveenDA** [comment]
Here the complete list of offically registered mime types.
http://www.iana.org/assignments/media-types/media-types.xhtml
