### ISSUE TITLE
.vdf MIME

### ISSUE THREAD

**Issue by Bizarrus** [jshttp/mime-db#78]
The MIME-Type for `.vdf` files don't exists in the Database.

**Extension:** `.vdf`
**Name:** `Valve Data File`
**Documentation:** https://developer.valvesoftware.com/wiki/KeyValues
**Conflicts:** `.vdf` will be used by `Avira` (https://www.avira.com/en/support-vdf-details)

**Comment by dougwilson** [comment]
I'm going to close this since no one has added it in over 6 months. I'm not even sure from those links what the MIME type is (you just noted the file extension), so I wasn't able to add it myself, either.
