### ISSUE TITLE
3gp support

### ISSUE THREAD

**Issue by ltomes** [jshttp/mime-db#89]
Hi, I have a local branch where I have added support for `3gp` files (Files that return a mime of 'video/3gp') But I don't seem to have permission to push my branch up to origin for PR.

Thanks for your time!

**Comment by dougwilson** [comment]
Hi @ltomes to contibute to GitHub repositories in general, you have to fork the repository, push to your fork, this create a pull request back in the original one based on your fork.

I found the following guide in the GitHub Bootcamp that should help explain the flow of doing this: https://help.github.com/articles/fork-a-repo/

**Comment by ltomes** [comment]
Thanks for the link Doug! I will push my changes to a fork and create a PR.
