### ISSUE TITLE
mime.lookup(audiofile.mp3)  get wrong mimetype and extension

### ISSUE THREAD

**Issue by salsx** [jshttp/mime-db#92]
filename = audiofile.mp3
mimetype: audio/mpeg
extension: mpga

temporary workaround is modify db.json (see below)

before:
  "audio/mpeg": {
    "source": "iana",
    "compressible": false,
    "extensions": ["mpga","mp2","mp2a","mp3","m2a","m3a"]

after:
  "audio/mpeg": {
    "source": "iana",
    "compressible": false,
    "extensions": ["mp3","mpga","mp2","mp2a","m2a","m3a"]

waiting your feedback.

Regards,
Giuseppe

**Comment by dougwilson** [comment]
I'm not sure what you mean; this module is just a JSON file so has no lookup method. The array of extensions is an unordered list, so changing the order doesn't convey any meaning here.

**Comment by salsx** [comment]
I tried to do this lookup -> mime.lookup("audiofile.mp3")   receiving this mimetype: audio/mpeg, and if try to get extension from this mime type audio/mpeg I've got mpga,    is right?

Thanks
Giuseppe

**Comment by dougwilson** [comment]
Hi @salsx I'm not sure; this module is just a JSON file, it doesn't have any methods to call to do lookups or anything. I believe you may be posted in the wrong module. If you look at what the name of the module you're `require()`ing in your code, just go to https://www.npmjs.com/ and look up the module. The right-hand side will have a link for where to report issues with that module. I hope that helps!
