### ISSUE TITLE
UTF-8 charset by default on "text/html"

### ISSUE THREAD

**Issue by Sterpa** [jshttp/mime-db#94]
Hi,
In the 21st century, UTF-8 became de facto the standard for www.
In order to not overwrite thousands of http-server, it's enough to change "text/html" to "text/html;charset=UTF-8" in mime-types by default.
This does not change the work of old html-documents in any way, but instantly includes the correct display of many-many new languages.

```
"text/html;charset=UTF-8": {
    "source": "iana",
    "compressible": true,
    "extensions": ["html","htm","shtml"]
}
```

**Comment by dougwilson** [comment]
Hi! The db.json file is auto generated from the upstream sources listed st the top of the readme. If the upstream is changed, this module will automatically pull in the change.
